In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("Dataset/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")
df2 = pd.read_csv("Dataset/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")
df3 = pd.read_csv("Dataset/Friday-WorkingHours-Morning.pcap_ISCX.csv")
df4 = pd.read_csv("Dataset/Monday-WorkingHours.pcap_ISCX.csv")
df5 = pd.read_csv("Dataset/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
df6 = pd.read_csv("Dataset/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv", encoding='latin-1', low_memory=False)
df7 = pd.read_csv("Dataset/Tuesday-WorkingHours.pcap_ISCX.csv")
df8 = pd.read_csv("Dataset/Wednesday-workingHours.pcap_ISCX.csv")

In [4]:
df2

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.12,35396,192.168.10.50,22,6,7/7/2017 1:00,1266342,41,44,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.16-192.168.10.50-60058-22-6,192.168.10.16,60058,192.168.10.50,22,6,7/7/2017 1:00,1319353,41,44,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.12,35396,192.168.10.50,22,6,7/7/2017 1:00,160,1,1,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.12-192.168.10.50-35398-22-6,192.168.10.12,35398,192.168.10.50,22,6,7/7/2017 1:00,1303488,41,42,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.12-192.168.10.50-35396-22-6,192.168.10.50,22,192.168.10.12,35396,6,7/7/2017 1:00,77,1,2,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286462,192.168.10.16-199.244.48.55-41926-443-6,192.168.10.16,41926,199.244.48.55,443,6,7/7/2017 3:29,196135,49,57,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
286463,192.168.10.16-199.244.48.55-41934-443-6,192.168.10.16,41934,199.244.48.55,443,6,7/7/2017 3:29,378424,49,59,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
286464,192.168.10.16-199.244.48.55-41932-443-6,192.168.10.16,41932,199.244.48.55,443,6,7/7/2017 3:29,161800,70,103,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
286465,192.168.10.16-199.244.48.55-41930-443-6,192.168.10.16,41930,199.244.48.55,443,6,7/7/2017 3:29,142864,50,62,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
286466,192.168.10.16-199.244.48.55-41928-443-6,192.168.10.16,41928,199.244.48.55,443,6,7/7/2017 3:29,186928,46,57,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [5]:
# обьеденяем

# df1["answer"] = 0
# df2["answer"] = 1
# df3["answer"] = 2
# df4["answer"] = 3
# df5["answer"] = 4
# df6["answer"] = 5
# df7["answer"] = 6
# df8["answer"] = 7

df = pd.concat([df1, df2, df3, df4, df5, df6, df7])
df

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.207.165,443.0,192.168.10.5,54865.0,6.0,7/7/2017 3:30,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.28.216,80.0,192.168.10.5,55054.0,6.0,7/7/2017 3:30,109.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.28.216,80.0,192.168.10.5,55055.0,6.0,7/7/2017 3:30,52.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.17.241.25,443.0,192.168.10.16,46236.0,6.0,7/7/2017 3:30,34.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.19.196.102,443.0,192.168.10.5,54863.0,6.0,7/7/2017 3:30,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445904,192.168.10.3-192.168.10.14-53-51694-17,192.168.10.14,51694.0,192.168.10.3,53.0,17.0,4/7/2017 10:09,155.0,2.0,2.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
445905,192.168.10.15-192.0.77.32-59317-443-6,192.0.77.32,443.0,192.168.10.15,59317.0,6.0,4/7/2017 4:41,110.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
445906,192.168.10.3-192.168.10.50-53-62256-17,192.168.10.50,62256.0,192.168.10.3,53.0,17.0,4/7/2017 9:11,166.0,2.0,2.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
445907,192.168.10.25-52.84.145.70-54726-443-6,52.84.145.70,443.0,192.168.10.25,54726.0,6.0,4/7/2017 12:48,81.0,1.0,1.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
445908,192.168.10.3-192.168.10.9-53-51801-17,192.168.10.9,51801.0,192.168.10.3,53.0,17.0,4/7/2017 10:38,202.0,2.0,2.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [6]:
for i in df.columns:
    df.rename(columns={i: i.strip()}, inplace=True)

In [7]:
df.groupby('Label').count()["Flow ID"]

Label
BENIGN                        1833066
Bot                              1966
DDoS                           128027
FTP-Patator                      7938
Infiltration                       36
PortScan                       158930
SSH-Patator                      5897
Web Attack  Brute Force         1507
Web Attack  Sql Injection         21
Web Attack  XSS                  652
Name: Flow ID, dtype: int64

In [8]:
print(df.columns)

Index(['Flow ID', 'Source IP', 'Source Port', 'Destination IP',
       'Destination Port', 'Protocol', 'Timestamp', 'Flow Duration',
       'Total Fwd Packets', 'Total Backward Packets',
       'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
       'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
       'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')